### ISSUE TITLE
KosmiczneCiekawostki: Tło video nie działa

### ISSUE THREAD

**Issue by Pawi1** [PerzotProgrammer/PerzotProgrammer.github.io#1]
![SS1](https://user-images.githubusercontent.com/114557817/215360040-8bd02e6c-46a3-4f78-987a-559866cd281a.png)
![SS2](https://user-images.githubusercontent.com/114557817/215360043-14c31101-aad5-47c2-903e-238f74db95a5.png)
![SS3](https://user-images.githubusercontent.com/114557817/215360132-26d972d2-e3f7-4e52-80db-4af8d62d87c7.png)

**Comment by PerzotProgrammer** [comment]
Działa tylko serwery do du**.
Próbuj na chromie
